### ISSUE TITLE
Functionalise Camera Feed Placeholder code

### ISSUE THREAD

**Issue by TehMaxwell** [AvalonROV/ROV_SW_GUI_2020#10]
Lines 90-96

In your top level constructor definition (UI class), you have some code for putting in place a camera feed placeholder that performs quite a few steps. I would place this in a seperate function.

**Comment by BenjaminJamesGriffiths** [comment]
Removed this code as it is no longer required. It was only used to paint an image on the camera feeds when the camera threads were not operational.
