### ISSUE TITLE
Config file - read Config File function

### ISSUE THREAD

**Issue by TehMaxwell** [AvalonROV/ROV_SW_GUI_2020#11]
The config file should have it's own class with all of the functionality required to read and manage the config file. Reading all of the parameters from the file in one function is inefficient if you want to change the config file during program execution. It also means that you are handling all of the variables individually within the main program code.

Inside a class the variables you need to store can just be attributes of the class, that way you can more easily access them by doing class_name.variable.

**Comment by BenjaminJamesGriffiths** [comment]
I have created a class that handles reading everything from the config xml file. Need to implement writing to the config file.

**Comment by BenjaminJamesGriffiths** [comment]
A library has been completed for reading and writing to the config file.
